### ISSUE TITLE
Create automation for checking for broken URLs

### ISSUE THREAD

**Issue by mpereira** [kudobuilder/kudo.dev#100]
I've used this in the past with great success: https://wummel.github.io/linkchecker/

We can initially just make it available via a `make` target or something, and eventually add it to a CI job.

**Comment by sharego** [comment]
Sounds great, I am using the website today for learnning, and got some url 404, i send a PR to fix. If there is CI auto check this everytime will be usefully. 

Which can be triggered on release, or some other properly time.

**Comment by kensipe** [comment]
Lets discuss... feedback from team mates is that this can often have numerous false positives... 
it is unclear about the maturity of the tooling.

**Comment by kensipe** [comment]
lets figure out a way to add value without chasing rainbows

**Comment by meichstedt** [comment]
Seems like this one is closed via #230
