### ISSUE TITLE
mailing list link broken

### ISSUE THREAD

**Issue by joshgav** [kudobuilder/kudo.dev#104]
**Which page is affected?**:

https://kudo.dev/community/

**What exactly is broken?**:

`Mailing List` link goes to a non-existent or private group. I receive the alert: "This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access." Here's a screenshot:

<img width="786" alt="Screen Shot 2019-11-26 at 3 18 00 PM" src="https://user-images.githubusercontent.com/4421720/69673562-2c0a5180-1060-11ea-8cb9-9c36ad7ac463.png">

**Which device do you use?**:

Chrome browser on Mac.

**Comment by gerred** [comment]
@joshgav Thanks. I updated the group visibility there, the labels don't make it clear what's private and what's public. Will you try again?

**Comment by gerred** [comment]
Confirmed as working by @joshgav in Slack. Thanks again!
