### ISSUE TITLE
Update/upgrade docs

### ISSUE THREAD

**Issue by alenkacz** [kudobuilder/kudo.dev#109]
**What would you like to be added**:
Add docs about how to update and upgrade your operator under features docs section. Make sure to explain what are update and upgrade plans and how to use them through CLI.

**Why is this needed**:

**Comment by kensipe** [comment]
we have some details in the runbook and we have operator specific docs (example: https://kudo.dev/docs/runbooks/kafka/upgrade.html)
We should promote update / upgrade in standard docs from a conceptual standpoint to augment the operator docs!
