### ISSUE TITLE
Enhance comparison between kudo and similar tools

### ISSUE THREAD

**Issue by techspeque** [kudobuilder/kudo.dev#117]
**What would you like to be added**:
At the moment the [comparison table page](https://kudo.dev/docs/comparison.html#comparison-table) does nicely compare the base features of KUDO vs other known tools however extra points could be added to clear up the context and explain how KUDO is unique versus the other tools. 

In addition a tools such as [kapitan](https://kapitan.dev) may not be seen initially as a direct competitor but I believe that it is in that region, so extension of that table with Kapitan would be rather useful 

**Why is this needed**:

Having headings such as: Project, Definition Language, Uses CRDs | Dependencies, Multi Step, Parameters without proper explanation of the context and why each feature is useful is making it difficult to understand from prospective user's perspective.

The more summarised context the better it is to understand, a fine balance between the amount of information (detail) and how informative and appropriate this information is, is rather necessary.

**Comment by kensipe** [comment]
@techspeque thanks for the issue... we will look at how we make updates to the site based on this feedback in the next release cycle.

**Comment by kensipe** [comment]
@techspeque The comparison section was recently overhauled..  it could be worth another look.

**Comment by kensipe** [comment]
Also... PR are welcome :)

**Comment by alenkacz** [comment]
Please reopen if current overhauled documentation is not enough
