### ISSUE TITLE
Docs say `kubectl kudo` plugin is optional but doesn't describe how to use KUDO without it

### ISSUE THREAD

**Issue by nfnt** [kudobuilder/kudo.dev#12]
**What would you like to be added**: Provide details on how to use KUDO without the `kubectl kudo` plugin or no longer mention that the plugin is optional.

**Comment by alenkacz** [comment]
I think even though you still can do a lot without CLI I am not sure it's really advised... @gerred ?

**Comment by nfnt** [comment]
[Most of the samples](https://github.com/kudobuilder/kudo/tree/master/config/samples) only work with `kubectl -f $sample.yaml`. I've created https://github.com/kudobuilder/kudo/issues/764 for this in KUDO.

**Comment by kensipe** [comment]
This seems like a low priority

**Comment by alenkacz** [comment]
I think we don't want to advertise using kudo without kudoctl that much. I would rather reopen this when there's a real user need pushing us to work without cli
