### ISSUE TITLE
Don't provide deployment YAMLs for KUDO as part of the docs, but as part of KUDO instead.

### ISSUE THREAD

**Issue by nfnt** [kudobuilder/kudo.dev#13]
In https://kudo.dev/docs/#install-kudo-into-your-cluster the YAMLs to deploy KUDO are provided as part of the docs. They should be distributed by https://github.com/kudobuilder/kudo instead to allow users to install them directly from a checked-out repo or tarball and to have developers change them directly in the repo.

**Comment by nfnt** [comment]
This might become obsolete with the new `kubectl kudo init` command.

**Comment by alenkacz** [comment]
oh we had this but we switched to docs. Actually with the release going out this week we're going to introduce `kudo init` ... but now I am not sure we already documented kudo init. @kensipe ?

**Comment by kensipe** [comment]
I plan on working on docs... including this one.  I expect to have it on Monday

**Comment by kensipe** [comment]
PR #23 resolves this issue
