### ISSUE TITLE
KUDO Comparison for Operator Developers

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#134]
**Description**

As a developer wanting to enable my users to deploy my application to Kubernetes, I want to compare the options for deploying software to Kubernetes clusters, so I can choose KUDO.

Each subsection of this document will have it's own task separated by paradigm, with example tools under that paradigm in a subheading.

**What should I expect to learn?**

By the end of the article, you will understand the differences between KUDO and other tools in the market, and where KUDO differentiates itself.

**What pre-requisite knowledge am I expected to have?**

General knowledge of what Kubernetes and config management concepts

## Estimated Length

- Long (700+ words)

# Metadata

- *Difficulty Level:* Beginner
- *Categories:*
- *Persona:*

**Comment by kensipe** [comment]
@gerred is this a comparison with operatorSDK and kubebuilder?  
are you looking for the same operator implemented in multiple ways for comparison?

**Comment by kensipe** [comment]
@tbaums is this something you or other SE/SA could provide some support on?

**Comment by gerred** [comment]
We have this now on the site.
