### ISSUE TITLE
Create a section for cluster operators that provides an overview how KUDO runs on a cluster. Architecture overview, security (RBAC)

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#136]

**Comment by nfnt** [comment]
This is covered by the components overview in #137. If it is covered well enough there, we don't need an extra section.

**Comment by kensipe** [comment]
feedback from the community is that this is an area of common questions... perhaps we need more details around this.   it also seems front and center with kubebuilder... but lacking details around kudo.

**Comment by kensipe** [comment]
we need to concerned:
1. details of security around kudo specifically
2. details of security and auth around a specific operator (likely a missing feature currently)

for instances... given an user 1 (admin) and user 2 (standard user).  how does user 1 have the ability to "backup" or "restore" and user 2 is restricted.

**Comment by kensipe** [comment]
@gerred @meichstedt the use case above ^^ likely needs to be prioritized into kudo
