### ISSUE TITLE
Create sections for KUDO concepts that have features. Also provides YAML and examples.

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#138]
- [x] Operator
- [x] Instance
- [x] Plans
- [x] Phase
- [x] Step
- [x] Tasks
  - [x] Pipe Task
  - [x] Apply Task
  - [x] Delete Task

**Comment by nrchakradhar** [comment]
@nfnt @gerred Where are the concepts explained? 
This https://kudo.dev/docs/concepts.html gives a blank page. Is it available for reading in Github somewhere? THANKS.

**Comment by gerred** [comment]
That's weird, we'll need to put a redirect in. Thanks @nrchakradhar - how'd you get linked to here?

https://kudo.dev/docs/what-is-kudo.html#main-concepts is the new page for that.

**Comment by nrchakradhar** [comment]
@gerred Thanks. I was exploring Kudo website as well as GitHub. I saw this issue was related to concepts so thought of checking once here.
Kudo is really very interesting and will try it out. Most of the documentation is really well organised.
