### ISSUE TITLE
🛬 Write "What is KUDO" introductory section

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#142]
**Name**

"What is KUDO" introductory section

**Description**

The landing page needs to immediately appeal to all types of users:

* Beginners who don’t know what an operator is - Newbies
* Human operators who want to run their application - Application operators
* Kubernetes experts who know about operators - Operator developers

The introductory section should speak to all of these, and include at least the following concepts at a high (yet specific) level:

* Operator pattern and the problems it addresses
* Stateless vs. stateful
* Operator development tooling
* How does KUDO help

## Estimated Length

- Short (300-500 words, possibly a few code snippets)

# Metadata

- *Difficulty Level:*
- *Categories:*
- *Persona:*

**Comment by mattj-io** [comment]
Use helm.sh as the template for layout

**Comment by yankcrime** [comment]
Done via #181
