### ISSUE TITLE
🛬 Landing page restructuring

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#143]
**Name**

Landing page restructuring

**Description**

The landing page needs restructuring to priorise content:

* Immediately explain what KUDO is and the problems it's designed to solve
* What someone can do with KUDO
* Workloads you can run with KUDO
* Who uses KUDO - should inspire confidence in the tool and its community

## Estimated Length

- Short (300-500 words, possibly a few code snippets)

# Metadata

- *Difficulty Level:*
- *Categories:*
- *Persona:*

**Comment by yankcrime** [comment]
Done via #181
