### ISSUE TITLE
🛬 What kind of workloads can you run with KUDO right now?

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#144]
**Name**

What kind of workloads can you run with KUDO right now?

We should emphasise and promote high-quality KUDO Operators that already exist.

**Description**

The landing page needs a section with logos of what can you run with
KUDO:

* Cassandra
* Spark
* Kafka
* Flink
* Zookeeper

Should be a bunch of logos with links to various projects.

## Estimated Length

- Short (300-500 words, possibly a few code snippets)

# Metadata

- *Difficulty Level:*
- *Categories:*
- *Persona:*

**Comment by yankcrime** [comment]
Closed via #181
