### ISSUE TITLE
🛬 Who is using KUDO?

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#145]
**Name**

Who is using KUDO?

**Description**

We need another section that highlights customers that are using KUDO
right now for various use-cases.  These could be technology companies
that are developing operators for their own services, as well as
companies that are using KUDO to manage other applications.

These should be companies that inspire confidence in anyone
potentially interested in KUDO.

* MayaData
* ArangoDB
* Salesforce
* Replicated.com

We might need a CTA via Slack.

## Estimated Length

- Short (300-500 words, possibly a few code snippets)

# Metadata

- *Difficulty Level:*
- *Categories:*
- *Persona:*

**Comment by mattj-io** [comment]
We will need to reach out to the folks who haven't agreed to this yet - I'm thinking Salesforce. Joerg told me we can't really use Arango. Are there any others I don't know about ? Who can reach out to Replicated.com ?
