### ISSUE TITLE
🛬 Write secondary sections

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#146]
**Name**

Write secondary sections expanding on:

* How do I get started?
* How do I write an operator?
* How do I deploy an application?
* Why do folks love KUDO?

**Description**

Describe the KUDO 'lifestyle' and why it makes things better for the problems it's designed to solve.

Some brief one or two line code snippets per context that get folks up
and running immediately with KUDO might be worthwhile here.

Possibly a short demo.

Links that hand off to other sections and salient bits of content.

## Estimated Length

- Medium (500-700 words, complex)

# Metadata

- *Difficulty Level:*
- *Categories:*
- *Persona:*

**Comment by mattj-io** [comment]
I think this should be a Getting Started page, too much content for a landing
