### ISSUE TITLE
Spark Runbooks:

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#152]
* [x] Launch a Spark Job
* [x] Viewing Spark Job output

**Comment by porridge** [comment]
This had already been done, see https://github.com/kudobuilder/operators/blob/master/repository/spark/docs/2.4.4-0.2.0/submission.md

**Comment by porridge** [comment]
Actually, we want these visible on kudo.dev, so reopening.

**Comment by porridge** [comment]
https://github.com/kudobuilder/operators/pull/224 is out to tune the markup for Spark.
