### ISSUE TITLE
Links are broken to the internal CLI pages

### ISSUE THREAD

**Issue by msdolbey** [kudobuilder/kudo.dev#295]
**Which page is affected?**:
https://kudo.dev/docs/

**What exactly is broken?**:
In the docs page, the link found here: https://kudo.dev/docs/#install-kudo-cli
and the link to kudo init documentation found here: https://kudo.dev/docs/#install-kudo-into-your-cluster
are broken

**Which device do you use?**:
Google chrome

**Anything else we need to know?**:
Just need to update these links.

**Comment by msdolbey** [comment]
created PR: 
https://github.com/kudobuilder/kudo.dev/pull/296

**Comment by porridge** [comment]
See also https://kubernetes.slack.com/archives/CG3HTFCMV/p1600443438001100
