### ISSUE TITLE
Add a note about comparison to Tekton to the docs

### ISSUE THREAD

**Issue by alenkacz** [kudobuilder/kudo.dev#72]
**What would you like to be added**:
Comparison page should mention how we differ from Tekton. This was one of the questions raised during the webinar.

**Why is this needed**:

**Comment by kensipe** [comment]
the comparison component of the site was overhauled during docathon week... 
@alenkacz is there a reason to compare to tekton specifically?   It seems like a different domain and more comparable to dispatch.   Closing for now... please reopen if desired.
