### ISSUE TITLE
Add support for RSS

### ISSUE THREAD

**Issue by yankcrime** [kudobuilder/kudo.dev#8]
**What would you like to be added**:

Support for RSS, in particular for the Community / Events section.

**Why is this needed**:

This has been requested by a couple of people as an easy way of being notified of any new or upcoming KUDO-related activities.

**Comment by meichstedt** [comment]
@yankcrime yeah that was on my list – I wanted to look into [vuepress-plugin-feed](https://github.com/webmasterish/vuepress-plugin-feed) for this.
