### ISSUE TITLE
Rename repository to kudo.dev

### ISSUE THREAD

**Issue by gerred** [kudobuilder/kudo.dev#92]
Just a thought - it's a bit more descriptive of which www we're actually talking about. :)

**Comment by meichstedt** [comment]
That's fine with me. I guess we'll need to adjust netlify conf in that case?

**Comment by gerred** [comment]
looking, I'm not sure...

**Comment by gerred** [comment]
I YOLO'ed it since it was the only way to test it, but I had to re-link the repo, so it's deploying now.

**Comment by gerred** [comment]
seems to have worked, now I can make the koi.dev repo! closing.
